### ISSUE TITLE
Broken compilation result in O2 mode

### ISSUE THREAD

**Issue by zetalog** [riscv-collab/riscv-gcc#197]
![memset](https://user-images.githubusercontent.com/3615765/94003035-47073880-fdcd-11ea-9628-01582120dff1.jpg)
![lockref_put_return](https://user-images.githubusercontent.com/3615765/94003082-5be3cc00-fdcd-11ea-80b4-5f5f12b72859.jpg)

Can clearly see compilation breakage in kernel/firmware builds.
Version 10.1.0, recent upstream (several days ago).

**Comment by aswaterman** [comment]
GCC is replacing a code sequence that's equivalent to `memset` with a call to `memset`.  Unfortunately, it's doing so within a `memset` routine, so the effect is an infinite loop.

You can suppress this behavior with the `-fno-builtin` flag.

Note this isn't a RISC-V-specific issue; I see the same behavior for x86-64 GCC.

**Comment by jim-wilson** [comment]
This can also be fixed with -fno-tree-loop-distribute-patterns which has a more limited effect than -fno-builtin, and is what newlib uses for all targets.

**Comment by zetalog** [comment]
Closing with recent version of riscv-gnu-toolchains.
