### ISSUE TITLE
How to make vector register load store across the stack in GCC

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-collab/riscv-gcc#221]
Recently, I am developing vector intrinsics and autovectorization in riscv for V-extension in my company. Our vector is so big and stack is limited, so I want to avoid vector load store across the stack. Can anyone help me with that? Thank you.

**Comment by jim-wilson** [comment]
You probably can't precvent the compiler from using stack.  But you can try carefully writing user code to minimize the amount of stack space used by the compiler.
