### ISSUE TITLE
How to autovectorize for pointer type variable

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-collab/riscv-gcc#233]
#include <stdint.h>
int result_C;
int result_D;
int Vector_A[10] [500];
int Vector_B[10] [500];

case 1:
void Vector_Multiply(int32_t *output, int32_t *output_02, int points)
{
    int i, j;
    for (j=0;j<10;j++)
    {
        for (i=0;i<points;i++)
        {
        	*output = (Vector_A[j][i]*( Vector_B[j][i]<<3)* (*output_02));
        }
    }
}

case 2:
int32_t Vector_Multiply_1(int32_t *output_02, int points )
{
    int i, j;
    int32_t output = 0;
    for (j=0;j<10;j++)
    {
        for (i=0;i<points;i++)
        {
        	output = Vector_A[j][i]*( Vector_B[j][i]<<3)* (*output_02);
        }
    }
    return output;
}

case 1:autovectorize fail:
missed: not vectorized: complicated access pattern.
case 2:autovectorize succeed

Here are two pieces of code, and their functionality almost no differences except the output in case 1 is a pointer type. But it fails
to autovectorize.  Do I have the chance to autovectorize for case 1? Thanks!

**Comment by kito-cheng** [comment]
This issue is not RISC-V specific issue, so I would suggest you sent this to gcc mailing list would be better.
