### ISSUE TITLE
riscv dejagnu fails

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-collab/riscv-gcc#238]
When I do the dejagnu regression with my own compiler (which I have developed some feature ).
It report these fails:
FAIL: gcc.dg/torture/pta-structcopy-1.c   -O1   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pta-structcopy-1.c   -O2   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pta-structcopy-1.c   -O3 -g   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pta-structcopy-1.c   -Os   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pta-structcopy-1.c   -O2 -flto -fno-use-linker-plugin -flto-partition=none   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pta-structcopy-1.c   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects   scan-tree-dump ealias "y.*, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074.c   -O1   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074.c   -O2   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074.c   -O3 -g   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074.c   -Os   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074.c   -O2 -flto -fno-use-linker-plugin -flto-partition=none   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074-2.c   -O1   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074-2.c   -O2   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074-2.c   -O3 -g   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074-2.c   -Os   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"
FAIL: gcc.dg/torture/pr39074-2.c   -O2 -flto -fno-use-linker-plugin -flto-partition=none   scan-tree-dump alias "y.._., points-to NULL, points-to vars: { D..... }"

The compilation succeed, is it a bug? Thanks

**Comment by jim-wilson** [comment]
You can use "make report" to check against the known list of failures.  This allow list is only occasionally updated.  Those don't look like known problems, so it might be a problem with your changes.  But these are all tests to check that pointer aliasing is working, so they might not be serious bugs if they are just causing optimizations to be missed.  You would have to look at the testcases to see what is wrong.
