### ISSUE TITLE
Inline asm problem in rvv

### ISSUE THREAD

**Issue by sh-zheng** [riscv-collab/riscv-gcc#313]
Hello, I use the gcc branch riscv-gcc-10.1-rvv-dev, and the compiler error "impossible constraint in 'asm'" occurs with the following code. I suspect the asm constraint code 'v' raise the error. Do we have supported the code 'v' in this branch?

    vfloat32m1_t v0, v1, v2;

	asm volatile(
        "vsetvli      zero, zero, e32, m1\n\t"
        "vfadd.vv     %0, %1, %2\n\t"
        :"=v"(v0)
        :"v"(v1), "v"(v2)
        :);

**Comment by kito-cheng** [comment]
GCC and LLVM both are using `vr` for vector register and `vm` for masking operand.

**Comment by sh-zheng** [comment]
> GCC and LLVM both are using `vr` for vector register and `vm` for vector masking operand.

That works. Thank you very much.

**Comment by kito-cheng** [comment]
Seems like you got the answered, so I close this issue :)
