### ISSUE TITLE
Is there a stable gcc10.2 branch which support RVV 1.0

### ISSUE THREAD

**Issue by fanghuaqi** [riscv-collab/riscv-gcc#320]
Hi there, 

Is there a gcc10.2 branch maintained provide good support for rvv 1.0(with intrinsic API support). I found https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-10.1-rvv-dev this branch is actively developed but it is gcc 10.1 based and I didn't know the status of this branch. Could anybody kindly point out it for me?

Thanks

**Comment by jim-wilson** [comment]
There is no actively maintained gcc rvv support, and no ongoing gcc rvv development.  Current work is all in LLVM, and LLVM is recommended if you want rvv support.  There is a guy at rivai.ai who claims to be working on gcc rvv 1.0 support for mainline FSF gcc, so maybe in a few months we will have something usable.  Rivai is in Shenzhen.

**Comment by fanghuaqi** [comment]
Thank you @jim-wilson , I will take a look at the upstream gcc, so the currently developed branch `riscv-gcc-10.1-rvv-dev` is not yet tested and proven?

**Comment by jim-wilson** [comment]
SiFive abandoned the gcc rvv work and is doing only llvm rvv work now.  The gcc rvv branch is badly out of date.  It should be mostly working, but is not compatible with rvv 1.0 or the current rvv intrinsics spec.

**Comment by rjiejie** [comment]
> Hi there,
> 
> Is there a gcc10.2 branch maintained provide good support for rvv 1.0(with intrinsic API support). I found https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-10.1-rvv-dev this branch is actively developed but it is gcc 10.1 based and I didn't know the status of this branch. Could anybody kindly point out it for me?
> 
> Thanks

We have also supported/maintained the RVV v1.0 feature, you could download prebuilt gcc toolchain from Alibaba website[1].

[1] : https://occ.t-head.cn/community/download?id=3988303250540531712

**Comment by lhtin** [comment]
> > Hi there,
> > Is there a gcc10.2 branch maintained provide good support for rvv 1.0(with intrinsic API support). I found https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-10.1-rvv-dev this branch is actively developed but it is gcc 10.1 based and I didn't know the status of this branch. Could anybody kindly point out it for me?
> > Thanks
> 
> We have also supported/maintained the RVV v1.0 feature, you could download prebuilt gcc toolchain from Alibaba website[1].
> 
> [1] : https://occ.t-head.cn/community/download?id=3988303250540531712

Do you have any plan to open source the RVV v1.0 feature?

**Comment by TommyMurphyTM1234** [comment]
Just to update this - Vector extension support is now being implemented/enhanced on the `rvv-next` branch.
Example build:
```
git clone https://github.com/riscv/riscv-gnu-toolchain rv64-linux-rvv-next -b rvv-next
cd rv64-linux-rvv-next
./configure --prefix=`pwd`/installed-tools --with-arch=rv64gcv
date > build.log; make linux 2>&1 | tee -a build.log; date >> build.log
```

**Comment by fanghuaqi** [comment]
Thanks @TommyMurphyTM1234 for the update

**Comment by troibe** [comment]
In case I (or someone else) run into this issue again.
The master branch of this repo has now support for the vector extension and the comment about `rvv-next` is irrelevant.

**Comment by kito-cheng** [comment]
Just leave few more comment for anyone who read this issue in future.

DO NOT USE `rvv-next` branch, it's *deprecated*, RVV intrinsic is supported since GCC 13 and auto vectorziation will supported in GCC 14.

**Comment by lldb123** [comment]
> Just leave few more comment for anyone who read this issue in future.
> 
> DO NOT USE `rvv-next` branch, it's _deprecated_, RVV intrinsic is supported since GCC 13 and auto vectorziation will supported in GCC 14.

Hello, I am currently using the main branch of this repo to compile riscv-gcc and it already can auto vectorize. 

When you say "RVV intrinsic is supported since GCC 13 and auto vectorziation will supported in GCC 14", does it mean GCC will supporting Vector Length Agnostic (VLA) vectorization?

**Comment by kito-cheng** [comment]
>  does it mean GCC will supporting Vector Length Agnostic (VLA) vectorization?

Yes, and you could give a try with [godbolt](https://godbolt.org/), use "risc-v (64-bits) gcc (trunk)" for compiler and "-march=rv64gcv -O3" for compilation flags
