### ISSUE TITLE
Question about how to release a  frozen RVV GCC with only RVV intrinsic support

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-collab/riscv-gcc#335]
Hi, as this PR:https://github.com/riscv-collab/riscv-gcc/pull/334 mentioned. This is the whole GCC our company open source which support both intrinsic and auto-vectorization. It seems that it is hard to push them GCC upstream directly because this PR change a lot in the middle end for auto-vectorization support. 
Recently, we are developing C++ overloaded functions and test them. I am planning to split a clean version with all dejagnu PASS that only support RVV intrinsic when the C++ overload feature is finished.  I make a new PR for this GCC for reviewers to review and then try to push them upstream. Is that appropriate? Since this version would be no middle-end change, I think it would be easier to push them upstream. Thank you~

**Comment by kito-cheng** [comment]
> I make a new PR for this GCC for reviewers to review and then try to push them upstream. Is that appropriate? 

Making a PR or sending that to upstream directly both are good to me :)
