### ISSUE TITLE
How can I make my GCC toolchain support both RVV and RVB?

### ISSUE THREAD

**Issue by Stark-qan** [riscv-collab/riscv-gcc#358]
Am I using the right configuration option?
`../configure --prefix=$RISCV --with-arch=rv64gcv_zba_zbb_zbc_zbs_zbkb_zbkc_zbkx --with-abi=lp64d`

**Comment by TommyMurphyTM1234** [comment]
Have you tried it?
You'll have to build from the `rvv-next` branch for vector support.
```
git clone https://github.com/riscv/riscv-gnu-toolchain rv64-linux-rvv-next -b rvv-next
```
This arch string seems to imply IMAFDC, vector extensions, bit manipulation extensions, and a subset of the cryptography extensions?
```
--with-arch=rv64gcv_zba_zbb_zbc_zbs_zbkb_zbkc_zbkx
```
* https://wiki.riscv.org/plugins/servlet/mobile?contentId=16458762#content/view/16458762

**Comment by TommyMurphyTM1234** [comment]
For what it's worth, this toolchain build worked successfully for me but I don't have to hand any test vector, bitmanip, crypto code to test...
```
git clone https://github.com/riscv/riscv-gnu-toolchain rv64gcvb-newlib -b rvv-next
cd rv64gcvb-newlib/
./configure --prefix=`pwd`/installed-tools --with-arch=rv64gcv_zba_zbb_zbc_zbs_zbkb_zbkc_zbkx
date > build.log; make 2>&1 | tee -a build.log; date >> build.log
```

**Comment by TommyMurphyTM1234** [comment]
@Stark-qan - can this issue be closed now? If so can you do it as I don't have privileges to do so in this repo? Thanks.

**Comment by Stark-qan** [comment]
Yes, thank you for your help
