### ISSUE TITLE
feature request: Support inline assembly with vector instructions

### ISSUE THREAD

**Issue by angsch** [riscv-collab/riscv-gcc#365]
_Issue was originally posted as https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1180 and was suggested to move here_

Hello,

We would be grateful if the next stable riscv-gcc release could support inline assembly with vector instructions. Currently, the latest stable release in the master branch does not allow clobbering vector registers.

```
#include <stdio.h>

int main(int argc, char **argv) {
    double a_ptr[10];
    for (int i = 0; i < 10; i++)
        a_ptr[i] = (double)(i + 1);

    // Zero-out the first vlenb/sizeof(double) entries
    asm volatile (
       " vsetvli zero, zero, e64, m1, ta, ma   \n\t"
       " fmv.d.x fa3, zero                     \n\t"
       " vfmv.v.f v0, fa3                      \n\t"
       " vse64.v v0, %[a_ptr]                  \n\t"
      :
      : [a_ptr] "m" (a_ptr)
      : "v0", "fa3"
    );

    // Expect the first vlenb/sizeof(double) to be zero
    for (int i = 0; i < 10; i++)
        printf("%.6e\n", a_ptr[i]);
}
```

```
$CC -v
[...]
gcc version 12.2.0 (g2ee5e430018) 
$CC -march=rv64iv -O1 main.c -static -Wall
main.c: In function 'main':
main.c:9:5: error: unknown register name 'v0' in 'asm'
```

The above code works with the riscv-gcc-rvv-next branch. Would it be possible to cherry-pick the commits that enable clobbering and include them in the next stable release?

**Comment by kito-cheng** [comment]
it supported on upstream now, so you could expect GCC 13 will support that, which will release around end of April.

**Comment by angsch** [comment]
Fantastic! Thank you
