### ISSUE TITLE
Error while compiling inline asm: impossible constraint in 'asm'

### ISSUE THREAD

**Issue by Chasing1020** [riscv-collab/riscv-gcc#375]
System info:

```bash
$ uname -a
Darwin zjcs-MacBook-Air.local 22.3.0 Darwin Kernel Version 22.3.0; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64
$ riscv64-unknown-elf-gcc --version
riscv64-unknown-elf-gcc (g2ee5e430018-dirty) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I'm tring to build a freestanding program to run in my SoC emulator. I using ebreak for debugging usage, if the a0 is set as 0, then it will print the value of the reg a1. Using the command `riscv64-unknown-elf-gcc -march=rv64g -ffreestanding -nostdlib -static -O2 -Wl,-Ttext=0 putchar.c -o putchar.out` and the code as follows:

```c
// putchar.c
static void ebreak(int arg0, int arg1) {
  asm volatile("addi a0, x0, %0;"
               "addi a1, x0, %1;"
               "ebreak" :: "i"(arg0), "i"(arg1));
}

static int putchar(char ch) {
  ebreak(0, ch);
  return ch;
}

static void exit() {
  asm volatile("unimp");
}

void _start() {
  char* s = "AB";
  for (int i = 0; i < 2; i++)
    putchar(s[i]);
  exit();
}
```

It works well when `char *s = "AB";`, however, when I trying to print a longer string like
```c
  char* s = "Hello, world!";
  for (int i = 0; i < 12; i++)
    putchar(s[i]);
```
It paniced with the message:
```bash
riscv64-unknown-elf-gcc -march=rv64g -ffreestanding -nostdlib -static -O2 -Wl,-Ttext=0 putchar.c -o putchar.out
In function 'ebreak',
    inlined from 'putchar' at putchar.c:8:3,
    inlined from 'main' at putchar.c:19:5:
putchar.c:2:3: warning: 'asm' operand 1 probably does not match constraints
    2 |   asm volatile("addi a0, x0, %0;"
      |   ^~~
putchar.c:2:3: error: impossible constraint in 'asm'
```

Am I doing something wrong here(may the wrong use of asm volatile?) and is there a way to make this work with the freestanding toolchain?
Any help would be greatly appreciated.

**Comment by cmuellner** [comment]
The `i` constraint is defined as "An immediate integer operand (one with constant value) is allowed. This includes symbolic constants whose values will be known only at assembly time or later.".

Your code has two issues:
* `arg0` and `arg1` are not known constants but parameters
* in the loop you don't have constants, but access array elements

Possible solution:
* Use `__attribute__((always_inline))` for functions that must be inlined
* Use `__attribute__((optimize("unroll-loops"))) or `-funroll-all-loops` to unroll the loop, which forwards the value to the array access

**Comment by Chasing1020** [comment]
> The `i` constraint is defined as "An immediate integer operand (one with constant value) is allowed. This includes symbolic constants whose values will be known only at assembly time or later.".
> 
> Your code has two issues:
> 
> * `arg0` and `arg1` are not known constants but parameters
> * in the loop you don't have constants, but access array elements
> 
> Possible solution:
> 
> * Use `__attribute__((always_inline))` for functions that must be inlined
> * Use `__attribute__((optimize("unroll-loops"))) or `-funroll-all-loops` to unroll the loop, which forwards the value to the array access


Thank you very much for your exceptionally detailed and informative reply! 

However, it seems that adding the `__attribute__` feature may not fully address the issue at hand. imo, I believe that relying solely on inline may only alleviate the symptoms and not address the underlying root cause. 
As I would like to make the `putchar` function that is versatile and not dependent on compiler attributes, may I kindly ask for your guidance in rethinking how to approach the implementation of this function?

**Comment by cmuellner** [comment]
I don't see why the immediate is necessary, therefore I would change the code as follows:
* Use `add` instead of `addi`
* Use `r` instead of `i` as the constraint

**Comment by Chasing1020** [comment]
Thank you again for your help. 
Use `r` is a good solution. I do need more studying on this topic.

**Comment by cmuellner** [comment]
Here is a link to the documentation: https://gcc.gnu.org/onlinedocs/gcc/Constraints.html
